[package]
name = "splash"
version = "0.1.0"
authors = ["orpheeantoniadis <orphee.antoniadis@gmail.com>"]

[lib]
name = "splash"
path = "src/splash.rs"
crate-type = ["staticlib"]

[dependencies]
ulibc = { path = "../ulibc" }

[profile.release]
lto = true
panic = 'abort'